### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by odyslam** [odyslam/home-urbit-anchor#1]
# Anchor

The anchor is a service that runs on the publicly accessible server and is the public gateway of Home-Urbit. Home-Urbit will route all outgoing traffic through the Anchor and all incoming traffic to Anchor will be routed to Home-Urbit (bypassing any local network restrictions). 

It is composed of the anchor server that runs on the server and the anchor client that runs on the device.

![](https://lucid.app/publicSegments/view/39099833-c22b-40e0-a9e9-65d2f62b6fe6/image.png)

## Features
- Routes all incoming traffic from the Anchor to Home-Urbit.
- Routes all outgoing traffic from Hom-Urbit through the Anchor.
- It's turn-key, meaning that you just point home-urbit to the anchor and it just works.

## Implementation details
- Urbit works at the IP/UDP level, thus it's not possible to use domain-based routing. Anchor must live at a specific IP.
- The service will be based on wireguard and connect to a wireguard node running on home-urbit
- The server will act as an exit node for home-urbit
- The deployment should be easily deployable via a simple script invocation.
	- service is containerized (wireguard, etc.)
	- Ansible script runs, connects to the API of some provider (e.g Hetzner), creates a VM, installs docker, runs the container.
- The deployment should receive as arguments:
	- The public key of the home-urbit wireguard node
	- The current IP of the wireguard node
	- What ports to forward( 34343 for ames, 80/433 for all HTTP based interfaces. home-urbit has subdomain-based routing, so we pipe all HTTP connections to Caddy.

## Milestones
- [ ] test wireguard tunnel for inbound and outbound
- [ ] test wiregaurd tunnel exit traffic
- [ ] create server container deployment
- [ ] create home-urbit container deployment
- [ ] automate linking of client to server
